build:

    environment:
        php:
            version: "5.4.28" # Common versions: 5.4.28, 5.5.12, or hhvm
            ini:
                'date.timezone': 'UTC'
        redis: false
        mysql: false

    dependencies:

        before:
            - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
            - cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && sed -i '$ a \\n[Phalcon]\nextension=phalcon.so\n'  /home/scrutinizer/.phpenv/versions/5.4.28/etc/php.ini
            - php -m | grep -i Phalcon
            - cd /home/scrutinizer/build
            - composer install --profile -o

    tests:
      override:
        - phpunit

filter:
    paths: [src/*]
    excluded_paths: [api/*, build/*, phpunit/*, vendor/*]

tools:
    php_mess_detector: true
    php_code_sniffer:
            config:
                standard: "PSR2" # Other Values: PSR2, PEAR, Zend, WordPress, Drupal, TYPO3CMS
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [api, buil, phpunit, vendor]
    php_cpd:
        enabled: true
        excluded_dirs: [api, build, phpunit, vendor]